<a href="https://colab.research.google.com/github/hikkaaaa/machine-learning/blob/main/scikit_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                        Scikit Learn
# **Train Test Split with Python Machine Learning**

This is a great method for prepping your data before you run a model

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
df = pd.read_csv('./drive/MyDrive/Colab Notebooks/hits.csv', encoding = 'latin-1')
df.head()

PLAYER  YRS     G     AB     R     H   2B   3B   HR   RBI    BB  \
0       Ty Cobb   24  3035  11434  2246  4189  724  295  117   726  1249   
1   Stan Musial   22  3026  10972  1949  3630  725  177  475  1951  1599   
2  Tris Speaker   22  2789  10195  1882  3514  792  222  117   724  1381   
3   Derek Jeter   20  2747  11195  1923  3465  544   66  260  1311  1082   
4  Honus Wagner   21  2792  10430  1736  3430  640  252  101     0   963   

     SO   SB   CS     BA  HOF  
0   357  892  178  0.366    1  
1   696   78   31  0.331    1  
2   220  432  129  0.345    1  
3  1840  358   97  0.310    1  
4   327  722   15  0.329    1

In [2]:
#splitting up the data, drop the player and HF
X = df.drop(columns = ['PLAYER', 'HOF'])
y = df['HOF']

In [3]:
X.head(), X.shape

(   YRS     G     AB     R     H   2B   3B   HR   RBI    BB    SO   SB   CS  \
 0   24  3035  11434  2246  4189  724  295  117   726  1249   357  892  178   
 1   22  3026  10972  1949  3630  725  177  475  1951  1599   696   78   31   
 2   22  2789  10195  1882  3514  792  222  117   724  1381   220  432  129   
 3   20  2747  11195  1923  3465  544   66  260  1311  1082  1840  358   97   
 4   21  2792  10430  1736  3430  640  252  101     0   963   327  722   15   
 
       BA  
 0  0.366  
 1  0.331  
 2  0.345  
 3  0.310  
 4  0.329  ,
 (465, 14))

In [4]:
y.head(), y.shape

(0    1
 1    1
 2    1
 3    1
 4    1
 Name: HOF, dtype: int64,
 (465,))

In [5]:
#build the training test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.2)

In [6]:
X_train.shape

(372, 14)

In [7]:
X_test.shape

(93, 14)

In [8]:
y_train.shape

(372,)

In [9]:
y_test.shape

(93,)

In [10]:
X_train.head()

YRS     G    AB     R     H   2B  3B   HR   RBI    BB    SO   SB   CS  \
46    17  2379  9073  1508  2724  504  80  210  1134  1032  1140  474  114   
460   15  1920  6653  1105  1665  285  39  291   964  1224  1427  225  101   
117   22  2435  8147  1283  2086  290  24  573  1584  1559  1699   19   18   
154   20  2586  9768  1582  2725  565  78  435  1587  1084  1795  312   49   
253   19  2084  7218   940  2091  484  66  191  1097   648   779  109   78   

        BA  
46   0.300  
460  0.250  
117  0.256  
154  0.279  
253  0.290

In [11]:
X_train.describe()

YRS            G            AB            R            H  \
count  372.000000   372.000000    372.000000   372.000000   372.000000   
mean    17.010753  2048.526882   7514.346774  1147.586022  2168.067204   
std      2.836020   359.608872   1293.124126   291.286912   414.856385   
min     11.000000  1331.000000   5472.000000   601.000000  1660.000000   
25%     15.000000  1798.750000   6531.500000   933.250000  1841.000000   
50%     17.000000  1988.000000   7221.000000  1099.000000  2076.500000   
75%     19.000000  2257.500000   8184.250000  1299.250000  2354.500000   
max     26.000000  3308.000000  12364.000000  2295.000000  3771.000000   

               2B          3B          HR          RBI           BB  \
count  372.000000  372.000000  372.000000   372.000000   372.000000   
mean   381.255376   77.854839  197.887097   877.158602   780.892473   
std     95.678746   47.958095  144.515151   493.051874   327.974695   
min    177.000000    8.000000   14.000000     0.000000   239.000000   
25%    313.000000   40.000000   75.000000   613.250000   527.000000   
50%    366.000000   66.500000  170.000000   963.000000   725.000000   
75%    436.250000  108.000000  291.000000  1207.250000   952.750000   
max    792.000000  252.000000  755.000000  2297.000000  2190.000000   

                SO           SB          CS          BA  
count   372.000000   372.000000  372.000000  372.000000  
mean    834.672043   195.032258   56.645161    0.288444  
std     486.213119   180.102903   46.660244    0.020682  
min       0.000000     8.000000    0.000000    0.246000  
25%     431.750000    59.750000   21.750000    0.273000  
50%     787.000000   140.500000   51.000000    0.287000  
75%    1197.250000   285.000000   84.000000    0.299250  
max    2597.000000  1406.000000  335.000000    0.358000

In [12]:
#you can now test the training with testing with the describe
X_train.describe().round(3)

YRS         G         AB         R         H       2B       3B  \
count  372.000   372.000    372.000   372.000   372.000  372.000  372.000   
mean    17.011  2048.527   7514.347  1147.586  2168.067  381.255   77.855   
std      2.836   359.609   1293.124   291.287   414.856   95.679   47.958   
min     11.000  1331.000   5472.000   601.000  1660.000  177.000    8.000   
25%     15.000  1798.750   6531.500   933.250  1841.000  313.000   40.000   
50%     17.000  1988.000   7221.000  1099.000  2076.500  366.000   66.500   
75%     19.000  2257.500   8184.250  1299.250  2354.500  436.250  108.000   
max     26.000  3308.000  12364.000  2295.000  3771.000  792.000  252.000   

            HR       RBI        BB        SO        SB       CS       BA  
count  372.000   372.000   372.000   372.000   372.000  372.000  372.000  
mean   197.887   877.159   780.892   834.672   195.032   56.645    0.288  
std    144.515   493.052   327.975   486.213   180.103   46.660    0.021  
min     14.000     0.000   239.000     0.000     8.000    0.000    0.246  
25%     75.000   613.250   527.000   431.750    59.750   21.750    0.273  
50%    170.000   963.000   725.000   787.000   140.500   51.000    0.287  
75%    291.000  1207.250   952.750  1197.250   285.000   84.000    0.299  
max    755.000  2297.000  2190.000  2597.000  1406.000  335.000    0.358

In [13]:
X_test.describe().round(3)

YRS         G         AB         R         H       2B       3B  \
count  93.000    93.000     93.000    93.000    93.000   93.000   93.000   
mean   17.204  2049.387   7499.892  1161.226  2178.968  379.742   81.355   
std     2.470   334.569   1304.786   284.219   461.932  100.160   54.815   
min    11.000  1332.000   4981.000   667.000  1666.000  186.000    3.000   
25%    16.000  1823.000   6503.000   961.000  1804.000  308.000   45.000   
50%    17.000  2002.000   7297.000  1117.000  2055.000  371.000   71.000   
75%    19.000  2215.000   8136.000  1284.000  2416.000  436.000   97.000   
max    24.000  3035.000  11434.000  2246.000  4189.000  724.000  309.000   

            HR       RBI        BB        SO       SB       CS      BA  
count   93.000    93.000    93.000    93.000   93.000   93.000  93.000  
mean   213.699   962.667   794.237   898.667  199.398   63.839   0.290  
std    140.045   453.825   326.800   500.474  189.619   53.028   0.023  
min      9.000     0.000   311.000    15.000    7.000    0.000   0.249  
25%     97.000   779.000   553.000   478.000   83.000   27.000   0.273  
50%    206.000   976.000   760.000   852.000  128.000   58.000   0.287  
75%    299.000  1183.000   965.000  1278.000  251.000   90.000   0.303  
max    548.000  1922.000  2019.000  1916.000  938.000  307.000   0.366

# **Python Feature Scaling in Scikit-Learn**


feature scaling - helps u to improve your models and their preformance by converting numerical values into the same exact scale



we have two ways of doing that - normalization and standardization

In [14]:
#we gonna drop "player", bcus we need numeric values and not strings
#we also gonna drop "cs", bcus we just dont need code stealing numbers
df = df.drop(columns = ['PLAYER', 'CS'])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   YRS     465 non-null    int64  
 1   G       465 non-null    int64  
 2   AB      465 non-null    int64  
 3   R       465 non-null    int64  
 4   H       465 non-null    int64  
 5   2B      465 non-null    int64  
 6   3B      465 non-null    int64  
 7   HR      465 non-null    int64  
 8   RBI     465 non-null    int64  
 9   BB      465 non-null    int64  
 10  SO      465 non-null    int64  
 11  SB      465 non-null    int64  
 12  BA      465 non-null    float64
 13  HOF     465 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 51.0 KB


In [16]:
df.describe().round(3)

YRS         G         AB         R         H       2B       3B  \
count  465.000   465.000    465.000   465.000   465.000  465.000  465.000   
mean    17.049  2048.699   7511.456  1150.314  2170.247  380.953   78.555   
std      2.765   354.392   1294.066   289.635   424.191   96.483   49.363   
min     11.000  1331.000   4981.000   601.000  1660.000  177.000    3.000   
25%     15.000  1802.000   6523.000   936.000  1838.000  312.000   41.000   
50%     17.000  1993.000   7241.000  1104.000  2076.000  366.000   67.000   
75%     19.000  2247.000   8180.000  1296.000  2375.000  436.000  107.000   
max     26.000  3308.000  12364.000  2295.000  4189.000  792.000  309.000   

            HR       RBI        BB        SO        SB       BA      HOF  
count  465.000   465.000   465.000   465.000   465.000  465.000  465.000  
mean   201.049   894.260   783.561   847.471   195.905    0.289    0.329  
std    143.623   486.193   327.432   489.224   181.846    0.021    0.475  
min      9.000     0.000   239.000     0.000     7.000    0.246    0.000  
25%     79.000   640.000   535.000   436.000    63.000    0.273    0.000  
50%    178.000   968.000   736.000   825.000   137.000    0.287    0.000  
75%    292.000  1206.000   955.000  1226.000   285.000    0.300    1.000  
max    755.000  2297.000  2190.000  2597.000  1406.000    0.366    2.000

In [17]:
X1 = df.iloc[:, 0:13]

In [18]:
X2 = df.iloc[:, 0:13]

# standardization

In [19]:
from sklearn.preprocessing import StandardScaler #standardiztion

In [20]:
scaleStandard = StandardScaler()

In [21]:
X1 = scaleStandard.fit_transform(X1) #apply standardization to X1
                                     #and overwrite X1 with the scaled result

In [22]:
X1 = pd.DataFrame(X1, columns = df.columns[0:13])

as you can see, the numbers have gotten less since we are trying to get the mean value 0 and standard deviation of 1 in the standardiztion

In [23]:
X1.head()

YRS         G        AB         R         H        2B        3B  \
0  2.516295  2.786078  3.034442  3.787062  4.764193  3.559333  4.389485   
1  1.792237  2.760655  2.677044  2.760530  3.444971  3.569709  1.996457   
2  1.792237  2.091184  2.075964  2.528955  3.171214  4.264876  2.909053   
3  1.068180  1.972543  2.849554  2.670665  3.055576  1.691719 -0.254611   
4  1.430208  2.099658  2.257758  2.024329  2.972977  2.687780  3.517449   

         HR       RBI        BB        SO        SB        BA  
0 -0.585841 -0.346449  1.423013 -1.003628  3.832067  3.648290  
1  1.909487  2.175837  2.493089 -0.309948 -0.649080  1.996159  
2 -0.585841 -0.350567  1.826585 -1.283965  1.299723  2.657012  
3  0.410896  0.858071  0.912434  2.030966  0.892346  1.004881  
4 -0.697364 -1.841290  0.548609 -1.065016  2.896201  1.901752

and as u can see, since we are trying to scale up to the standardization, we need to have the mean value 0 and standard deviation 1, which is the exact case below

In [24]:
X1.describe().round(3)

YRS        G       AB        R        H       2B       3B       HR  \
count  465.000  465.000  465.000  465.000  465.000  465.000  465.000  465.000   
mean    -0.000    0.000    0.000    0.000    0.000    0.000   -0.000   -0.000   
std      1.001    1.001    1.001    1.001    1.001    1.001    1.001    1.001   
min     -2.190   -2.027   -1.958   -1.899   -1.204   -2.116   -1.532   -1.339   
25%     -0.742   -0.697   -0.765   -0.741   -0.784   -0.715   -0.762   -0.851   
50%     -0.018   -0.157   -0.209   -0.160   -0.222   -0.155   -0.234   -0.161   
75%      0.706    0.560    0.517    0.504    0.483    0.571    0.577    0.634   
max      3.240    3.557    3.754    3.956    4.764    4.265    4.673    3.861   

           RBI       BB       SO       SB       BA  
count  465.000  465.000  465.000  465.000  465.000  
mean     0.000    0.000   -0.000    0.000    0.000  
std      1.001    1.001    1.001    1.001    1.001  
min     -1.841   -1.665   -1.734   -1.040   -2.016  
25%     -0.524   -0.760   -0.842   -0.732   -0.742  
50%      0.152   -0.145   -0.046   -0.324   -0.081  
75%      0.642    0.524    0.775    0.490    0.533  
max      2.888    4.300    3.580    6.662    3.648

# normalization

In [25]:
from sklearn.preprocessing import MinMaxScaler

In [26]:
scaleMinMax = MinMaxScaler(feature_range = (0, 1))

In [27]:
X2 = scaleMinMax.fit_transform(X2)

In [28]:
X2 = pd.DataFrame(X2, columns = df.columns[0:13])

in normalizartion, all the values should be between 0 and 1, which is the case here as u can see

In [29]:
X2.head()

YRS         G        AB         R         H        2B        3B  \
0  0.866667  0.861912  0.874035  0.971074  1.000000  0.889431  0.954248   
1  0.733333  0.857360  0.811459  0.795750  0.778964  0.891057  0.568627   
2  0.733333  0.737481  0.706217  0.756198  0.733096  1.000000  0.715686   
3  0.600000  0.716237  0.841663  0.780401  0.713721  0.596748  0.205882   
4  0.666667  0.738998  0.738047  0.670012  0.699881  0.752846  0.813725   

         HR       RBI        BB        SO        SB        BA  
0  0.144772  0.316064  0.517683  0.137466  0.632595  1.000000  
1  0.624665  0.849369  0.697078  0.268002  0.050751  0.708333  
2  0.144772  0.315194  0.585341  0.084713  0.303788  0.825000  
3  0.336461  0.570744  0.432086  0.708510  0.250893  0.533333  
4  0.123324  0.000000  0.371092  0.125915  0.511079  0.691667

as u can see, max is 1 and min is 0

In [30]:
X2.describe().round(3)

YRS        G       AB        R        H       2B       3B       HR  \
count  465.000  465.000  465.000  465.000  465.000  465.000  465.000  465.000   
mean     0.403    0.363    0.343    0.324    0.202    0.332    0.247    0.257   
std      0.184    0.179    0.175    0.171    0.168    0.157    0.161    0.193   
min      0.000    0.000    0.000    0.000    0.000    0.000    0.000    0.000   
25%      0.267    0.238    0.209    0.198    0.070    0.220    0.124    0.094   
50%      0.400    0.335    0.306    0.297    0.164    0.307    0.209    0.227   
75%      0.533    0.463    0.433    0.410    0.283    0.421    0.340    0.379   
max      1.000    1.000    1.000    1.000    1.000    1.000    1.000    1.000   

           RBI       BB       SO       SB       BA  
count  465.000  465.000  465.000  465.000  465.000  
mean     0.389    0.279    0.326    0.135    0.356  
std      0.212    0.168    0.188    0.130    0.177  
min      0.000    0.000    0.000    0.000    0.000  
25%      0.279    0.152    0.168    0.040    0.225  
50%      0.421    0.255    0.318    0.093    0.342  
75%      0.525    0.367    0.472    0.199    0.450  
max      1.000    1.000    1.000    1.000    1.000

# **One Hot Encoder**

In [31]:
d = {'sales': [100000, 222000, 1000000, 522000, 11111, 222222, 75000, 90000, 5222200],
     'city': ['Tampa', 'Tampa', 'Orlando', 'Jacksonvile', 'Orlando', 'Jacksonvile', 'Tampa', 'Orlando', 'Tampa'],
     'size': ['Small', 'Medium', 'Large', 'Small', 'Large', 'Large', 'Medium', 'Small', 'Medium']}

In [33]:
df = pd.DataFrame(d)

In [34]:
df

sales         city    size
0   100000        Tampa   Small
1   222000        Tampa  Medium
2  1000000      Orlando   Large
3   522000  Jacksonvile   Small
4    11111      Orlando   Large
5   222222  Jacksonvile   Large
6    75000        Tampa  Medium
7    90000      Orlando   Small
8  5222200        Tampa  Medium

In [36]:
df['city'].unique()

array(['Tampa', 'Orlando', 'Jacksonvile'], dtype=object)

In [37]:
#one hot encoder is gonna expand the table with all the city unique values
#(we chose 'city', because it doesnt contain numeric values and unlike size,
#we are not able to count it)
from sklearn.preprocessing import OneHotEncoder

In [39]:
ohe = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False).set_output(transform = 'pandas')

In [40]:
ohetransform = ohe.fit_transform(df[['city']])

In [41]:
ohetransform

city_Jacksonvile  city_Orlando  city_Tampa
0               0.0           0.0         1.0
1               0.0           0.0         1.0
2               0.0           1.0         0.0
3               1.0           0.0         0.0
4               0.0           1.0         0.0
5               1.0           0.0         0.0
6               0.0           0.0         1.0
7               0.0           1.0         0.0
8               0.0           0.0         1.0

In [42]:
df.head()

sales         city    size
0   100000        Tampa   Small
1   222000        Tampa  Medium
2  1000000      Orlando   Large
3   522000  Jacksonvile   Small
4    11111      Orlando   Large

In [44]:
ohetransform.head()

city_Jacksonvile  city_Orlando  city_Tampa
0               0.0           0.0         1.0
1               0.0           0.0         1.0
2               0.0           1.0         0.0
3               1.0           0.0         0.0
4               0.0           1.0         0.0

In [45]:
df = pd.concat([df, ohetransform], axis = 1).drop(columns = ['city'])

In [46]:
df

sales    size  city_Jacksonvile  city_Orlando  city_Tampa
0   100000   Small               0.0           0.0         1.0
1   222000  Medium               0.0           0.0         1.0
2  1000000   Large               0.0           1.0         0.0
3   522000   Small               1.0           0.0         0.0
4    11111   Large               0.0           1.0         0.0
5   222222   Large               1.0           0.0         0.0
6    75000  Medium               0.0           0.0         1.0
7    90000   Small               0.0           1.0         0.0
8  5222200  Medium               0.0           0.0         1.0

# **Ordial Encoder with Python ML**

In [48]:
d = {'sales': [100000, 222000, 1000000, 522000, 11111, 222222, 75000, 90000, 5222200],
     'city': ['Tampa', 'Tampa', 'Orlando', 'Jacksonvile', 'Orlando', 'Jacksonvile', 'Tampa', 'Orlando', 'Tampa'],
     'size': ['Small', 'Medium', 'Large', 'Small', 'Large', 'Large', 'Medium', 'Small', 'Medium']}

In [50]:
df = pd.DataFrame(d)

In [52]:
df.head()

sales         city    size
0   100000        Tampa   Small
1   222000        Tampa  Medium
2  1000000      Orlando   Large
3   522000  Jacksonvile   Small
4    11111      Orlando   Large

In [53]:
#we gonna use size, since there is no specific order
df['size'].unique()

array(['Small', 'Medium', 'Large'], dtype=object)

In [54]:
sizes = ['Small', 'Medium', 'Large']

In [55]:
from sklearn.preprocessing import OrdinalEncoder

In [56]:
enc = OrdinalEncoder(categories = [sizes])

In [58]:
enc.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [1.],
       [0.],
       [1.]])

In [60]:
df['size'] = enc.fit_transform(df[['size']])

In [61]:
df.head()

sales         city  size
0   100000        Tampa   0.0
1   222000        Tampa   1.0
2  1000000      Orlando   2.0
3   522000  Jacksonvile   0.0
4    11111      Orlando   2.0

In [ ]:
#0 - small,1 - medium, 2 - large

# **Handling Missing Data with simple imputer**

In [62]:
import numpy as np

In [63]:
miles = pd.DataFrame({'farthest_run_mi': [50.0, 62.0, np.nan, 100.0, 26.0, 13.0, 31.0, 50.0]})

In [64]:
miles

farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [65]:
miles.isna()

farthest_run_mi
0            False
1            False
2             True
3            False
4            False
5            False
6            False
7            False

In [66]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [67]:
from sklearn.impute import SimpleImputer

In [68]:
#filling missing values with eman
imp_mean = SimpleImputer(strategy = 'mean')

In [69]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [70]:
#filling missing values with median, the most common one
imp_median = SimpleImputer(strategy = 'median')

In [71]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [72]:
#filling missing values with the most common value in the dataset
imp_mode = SimpleImputer(strategy = 'most_frequent')

In [73]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [75]:
#filling missing vlaues with the constant value, the value is 13 in this case
imp_constant = SimpleImputer(strategy = 'constant', fill_value = 13)

In [76]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [82]:
#filling the missing value in the categorical data
names = pd.DataFrame({'names': ['Jackson', 'Nowlan', 'Honus', 'Some', np.nan, 'Ruth']})

In [78]:
names

names
0  Jackson
1   Nowlan
2    Honus
3     Some
4      NaN
5     Ruth

In [79]:
imp_constant_cat = SimpleImputer(strategy = 'constant', fill_value = 'babe')

In [81]:
imp_constant_cat.fit_transform(names)

array([['Jackson'],
       ['Nowlan'],
       ['Honus'],
       ['Some'],
       ['babe'],
       ['Ruth']], dtype=object)

In [83]:
#gonna buils a brand new column with 0s and 1s, 1 - nan value
imp_mean_marked = SimpleImputer(strategy = 'mean', add_indicator = True)

In [84]:
imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [85]:
#more advanced dataset version
#(changing th missing values in both categorical and numerical at the same time)
df = pd.DataFrame({
    'Name': ['Ryan', 'Nolan', 'Walter', 'Honus', 'Christy', np.nan, 'Napoleon', 'Tris'],
    'farthest_run_mi': [50.0, 62.0, np.nan, 100.0, 26.0, 13.0, 31.0, 50.0]
})

In [86]:
df

Name  farthest_run_mi
0      Ryan             50.0
1     Nolan             62.0
2    Walter              NaN
3     Honus            100.0
4   Christy             26.0
5       NaN             13.0
6  Napoleon             31.0
7      Tris             50.0

In [87]:
from sklearn.compose import make_column_transformer

In [88]:
ct = make_column_transformer(
    (imp_constant_cat, ['Name']),
    (imp_mean, ['farthest_run_mi']),
    remainder = 'drop'
)

In [89]:
ct.set_output(transform = 'pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='babe',
                                               strategy='constant'),
                                 ['Name']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['farthest_run_mi'])])

In [91]:
df_pandas = ct.fit_transform(df)

In [92]:
df_pandas

simpleimputer-1__Name  simpleimputer-2__farthest_run_mi
0                  Ryan                         50.000000
1                 Nolan                         62.000000
2                Walter                         47.428571
3                 Honus                        100.000000
4               Christy                         26.000000
5                  babe                         13.000000
6              Napoleon                         31.000000
7                  Tris                         50.000000

# **Simplify Data Preprocessing with Python's Column Transformer**

In [93]:
d = {'sales': [100000, 222000, 1000000, 522000, 11111, 222222, 75000, 90000, 5222200],
     'city': ['Tampa', 'Tampa', 'Orlando', 'Jacksonvile', 'Orlando', 'Jacksonvile', 'Tampa', 'Orlando', 'Tampa'],
     'size': ['Small', 'Medium', 'Large', 'Small', 'Large', 'Large', 'Medium', 'Small', 'Medium']}

In [94]:
df = pd.DataFrame(d)

In [95]:
df

sales         city    size
0   100000        Tampa   Small
1   222000        Tampa  Medium
2  1000000      Orlando   Large
3   522000  Jacksonvile   Small
4    11111      Orlando   Large
5   222222  Jacksonvile   Large
6    75000        Tampa  Medium
7    90000      Orlando   Small
8  5222200        Tampa  Medium

In [97]:
#transforming city with one hot encoder and size with ordinal encoder
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [98]:
ohe = OneHotEncoder(sparse_output = False)

In [99]:
ode = OrdinalEncoder()

In [100]:
from sklearn.compose import make_column_transformer

In [101]:
ct = make_column_transformer(
    (ohe, ['city']),
    (ode, ['size']),
    remainder = 'passthrough'
)

In [102]:
ct.set_output(transform = 'pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder',
                                 OneHotEncoder(sparse_output=False), ['city']),
                                ('ordinalencoder', OrdinalEncoder(), ['size'])])

In [104]:
df_pandas = ct.fit_transform(df)

In [105]:
df_pandas

onehotencoder__city_Jacksonvile  onehotencoder__city_Orlando  \
0                              0.0                          0.0   
1                              0.0                          0.0   
2                              0.0                          1.0   
3                              1.0                          0.0   
4                              0.0                          1.0   
5                              1.0                          0.0   
6                              0.0                          0.0   
7                              0.0                          1.0   
8                              0.0                          0.0   

   onehotencoder__city_Tampa  ordinalencoder__size  remainder__sales  
0                        1.0                   2.0            100000  
1                        1.0                   1.0            222000  
2                        0.0                   0.0           1000000  
3                        0.0                   2.0            522000  
4                        0.0                   0.0             11111  
5                        0.0                   0.0            222222  
6                        1.0                   1.0             75000  
7                        0.0                   2.0             90000  
8                        1.0                   1.0           5222200

In [106]:
#if you do remainder = 'drop' ,then u will not have a remainder_sales column